all:
    vars:
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  
  zookeeper:
    hosts:
      216.58.200.131:
        internal_ip: 10.0.2.4
      172.217.26.195:
        internal_ip: 10.0.2.5
      216.58.200.131:
        internal_ip: 10.0.2.6
  kafka_broker:
    hosts:
      216.58.200.131:
      172.217.26.195:
      216.58.200.131:
  
  schema_registry:
    hosts:
      216.58.200.131:
  control_center:
    hosts:
      172.217.26.195: